export const darkDesign = {
  colors: {
    accent: '#3ecf8e',
    accentDeep: '#24b47e',
    accentSoft: '#7ee2b8',
    canvas: '#111315',
    canvasRaised: '#17191c',
    canvasRaisedSoft: '#1d2024',
    canvasInset: '#0d0f11',
    panel: '#1a1d21',
    panelStrong: '#20242a',
    border: '#2a2f36',
    borderStrong: '#3b424b',
    text: '#f3f4f6',
    textMuted: '#9ca3af',
    textSoft: '#cfd4dc',
    textFaint: '#69707a',
    danger: '#ff7a7a',
    warning: '#f7cd61',
    success: '#73d9a0',
    onAccent: '#0b0f0d',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 24,
    xxl: 32,
    huge: 48,
  },
  radii: {
    sm: 6,
    md: 8,
    lg: 12,
    xl: 16,
    pill: 999,
  },
  typography: {
    hero: {
      fontSize: 34,
      fontWeight: '600' as const,
      letterSpacing: -0.9,
      lineHeight: 38,
    },
    title: {
      fontSize: 26,
      fontWeight: '600' as const,
      letterSpacing: -0.5,
      lineHeight: 30,
    },
    section: {
      fontSize: 18,
      fontWeight: '600' as const,
      letterSpacing: -0.2,
      lineHeight: 22,
    },
    body: {
      fontSize: 15,
      lineHeight: 22,
    },
    caption: {
      fontSize: 13,
      lineHeight: 18,
    },
    micro: {
      fontSize: 12,
      lineHeight: 16,
    },
    button: {
      fontSize: 14,
      fontWeight: '600' as const,
      letterSpacing: 0.1,
    },
  },
  shadows: {
    card: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 12 },
      shadowOpacity: 0.24,
      shadowRadius: 24,
      elevation: 8,
    },
    soft: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.16,
      shadowRadius: 14,
      elevation: 4,
    },
  },
} as const;
